(define (squarer a b)
    (define (process-new-value)
        (if (has-value? b)
            (if (< (get-value b) 0)
                (error "square less than 0: SQUARER" (get-value b))
                (set-value! a (sqrt (get-value b)))
            )
            (if (has-value? a)
                (set-value! b (square (get-value a)))
                'ok
            )
        )
    )
    (define (process-forget-value)
        (forget-value! a me)
        (forget-value! b me)
        (process-new-value)
    )
    (define (me request)
        (cond
            ((eq? request 'I-have-a-value))
            ((eq? request 'I-lost-my-value))
            (else (error "Unknown request: ADDER" request))
        )
    )
    ⟨rest of definition⟩
    me
)
